### ISSUE TITLE
Add OSGi headers to manifest

### ISSUE THREAD

**Issue by tobias--** [j-easy/easy-batch#283]
It would be nice to be able to use easy batch in an OSGi context out of the box. Currently, I wrap the jars using bnd.

A quick way to turn the jars into OSGi compatible bundles is using the [Apache Felix Maven Bundle Plugin](https://felix.apache.org/documentation/subprojects/apache-felix-maven-bundle-plugin-bnd.html).

**Comment by benas** [comment]
Sure! let me plan that for next release.

If you have experience with this plugin, don't hesitate to submit a pull request, I'll be happy to merge it.

Kind regards
Mahmoud

**Comment by benas** [comment]
Hi @tobias-- 

I've added OSGi headers to MANIFEST in all artifacts.
Can you give it a try in version 5.2.0-SNAPSHOT and tell me if this is ok for you?

Kr
Mahmoud

**Comment by tobias--** [comment]
Hi @benas,

is there a binary of the snapshot so I could have a quick look? I did not see any artifacts being archived by travis. I built the master quickly using ```mvn clean install``` but it does not seem to contain any OSGi-Headers (like "Bundle-SymbolicName" or "Export-Package").

**Comment by benas** [comment]
Hi @tobias-- 

Sorry, my mistake. The manifest was correctly generated by maven-bundle-plugin but was overriden with the default one generated by maven-jar-plugin. I've just fixed the issue and it should be fine, it works on my machine 😜

Unfortunately, I cannot publish a snapshot version right now. Can you pull the latest master branch and try again? This would be very kind! Thank you for your time.

Kr
Mahmoud

**Comment by tobias--** [comment]
Hi @benas,

the jars contain the expected headers and they seem to be correct. Great! Thank you! Unfortunately I don't have the time to verify it in a real life project right now, but I'd say this issue can be closed for now.

**Comment by benas** [comment]
Great! thank you for taking time to test 👍 

I'll include these headers in v5.2.
We can always fix any issue if any in v5.3 or later.
