### ISSUE TITLE
Add support for Kafka

### ISSUE THREAD

**Issue by raulgomis** [j-easy/easy-batch#284]
It would be nice to have support for Kafka components: Reader, Writer, etc.

**Comment by benas** [comment]
This was in my todo list since I added support for JMS, but I never had time to work on it.

Kafka is awesome and it would be great to have an extension for it.

If you are comfortable with Kafka APIs, you are welcome to submit a pull request. There are only a couple of interfaces to implement. This would be a fantastic contribution!

Let me plan that for next release.

**Comment by raulgomis** [comment]
Sure! I have some experience with Kafka and I could help in my free time (that is not that much at the moment :( ). Btw, what is the difference in project organization between the module "easybatch-extensions" and the other root level ones, such as "easybatch-jms"? Where should I place the kafka one?

**Comment by benas** [comment]
Oh great news! you are welcome. Do it on your own pace, no worries.

root level modules are for core java (EE) APIs (jdbc, jms, jpa, etc ).
Integrations with third party tools should go under easybatch-extensions.

So for kafka, it should be in the extensions directory (BTW, I add a 'extension' label on the issue if it is a new extension that is requested).

**Comment by benas** [comment]
@raulgomis Still willing to contribute a Kafka record reader/writer to Easy Batch?

FTR, I contributed to adding kafka support in Spring Batch and could do it here too. but since you offered to help, I want to give the credit to you, unless you tell me otherwise.

Looking forward to your reply.

**Comment by raulgomis** [comment]
Hey @benas ! 

Thanks for asking! I have an initial version in my fork, I'll finish it during next week and create a PR so that we can discuss it.

Regards,
Raul

**Comment by benas** [comment]
Hi @raulgomis ,

If you are still interested in contributing Kafka record reader/writer, please do it in a repo on your side and I will be more than happy to add a reference to it in the home page.

Thank you!

Best regards,
Mahmoud
