### ISSUE TITLE
Add support for Cassandra DB

### ISSUE THREAD

**Issue by raulgomis** [j-easy/easy-batch#285]
It would be nice to add support for Cassandra: Reader, Writer, etc.

**Comment by benas** [comment]
Just like kafka support being in the todo list after adding support for JMS, I always wanted to add support for cassandra as I did for mongo db.

It would be nice to have cassandra support indeed, but time is the only resource missing!

Any contribution is welcome.

**Comment by benas** [comment]
As discussed in #288 in regards to the maintenance burden, I'm closing this issue for now. Contributions are welcome to add support for third party libraries and tools.
