### ISSUE TITLE
Throttle throughput

### ISSUE THREAD

**Issue by MALPI** [j-easy/easy-batch#290]
Hi there,

is it possible to throttle the throughput of a batch job? 

I saw that there is the batch size which is at least limiting the size per Batch. But this is not what I am looking for. 

Let's assume you need to call a 3rd party within your batchjob and you don't want to put too much stress on it. Therefore you want to make sure that you don't process more then 10 records per second.

I hope you got what I mean?

**Comment by benas** [comment]
Hi @MALPI 

Thank you for opening this issue. This is actually an awesome feature if we have it!

I was thinking of implementing it using a decorator of the RecordReader (Something like the `RetryableRecordReader`). The reader would throttle items as needed.

What do you think?

Kind regards
Mahmoud

**Comment by MALPI** [comment]
Hey @benas this probably makes sense. I am just wondering if you are able to recognize how many records are processed.

Best

**Comment by benas** [comment]
Yes you can use a reader listener and count how much records goes through it.

Actually the correct answer depends on where in the pipeline are you calling the 3rd party service.

Using a reader decorator is one possibility, but you can also implement the throtteling using a listener after reading records, inside the pipeline or before writing records. Do you see?

**Comment by MALPI** [comment]
In any case this has to happen **before** records are written.

**Comment by benas** [comment]
Hi,

I was trying to implement your requirement in a simple way (as a starting point) to see if we could make it.

### Using a record reader decorator

Here is the reader:

```java
public class ThrottlingRecordReader implements RecordReader {

    private RecordReader delegate;
    private int duration;

    public ThrottlingRecordReader(RecordReader delegate, int duration) {
        this.delegate = delegate;
        this.duration = duration;
    }

    @Override
    public void open() throws Exception {
        delegate.open();
    }

    @Override
    public Record readRecord() throws Exception {
        Thread.sleep(duration);
        return delegate.readRecord();
    }

    @Override
    public void close() throws Exception {
        delegate.close();
    }

}
```

and how to use it:

```java
    @Test
    public void testRecordThrottlingUsingReaderDecorator() {
        List<Integer> dataSource = new ArrayList<>();
        for (int i = 1; i <= 20; i++) {
            dataSource.add(i);
        }

        Job job = JobBuilder.aNewJob()
                .reader(new ThrottlingRecordReader(new IterableRecordReader(dataSource), 100))
                .reader(new IterableRecordReader(dataSource))
                .writer(new StandardOutputRecordWriter())
                .batchSize(10)
                .build();

        JobExecutor jobExecutor = new JobExecutor();
        JobReport jobReport = jobExecutor.execute(job);
        jobExecutor.shutdown();
        Assertions.assertThat(jobReport.getMetrics().getDuration()).isGreaterThanOrEqualTo(2 * 1000); // more than 2seconds
    }
```

The combination of batch size = 10 and a duration = 100ms we can achieve 10 records per seconds.

### Using a record writer listener:

```java
    @Test
    public void testRecordThrottlingUsingWriterListener() {
        List<Integer> dataSource = new ArrayList<>();
        for (int i = 1; i <= 20; i++) {
            dataSource.add(i);
        }

        Job job = JobBuilder.aNewJob()
                //.reader(new ThrottlingRecordReader(new IterableRecordReader(dataSource), 100))
                .reader(new IterableRecordReader(dataSource))
                .writerListener(new RecordWriterListener() {
                    @Override
                    public void beforeRecordWriting(Batch batch) {
                        try {
                            Thread.sleep(1000); // wait 1 second before writing 10 records => 10 records per second
                        } catch (InterruptedException e) {
                            throw new RuntimeException(e);
                        }
                    }

                    @Override
                    public void afterRecordWriting(Batch batch) {

                    }

                    @Override
                    public void onRecordWritingException(Batch batch, Throwable throwable) {

                    }
                })
                .writer(new StandardOutputRecordWriter())
                .batchSize(10)
                .build();

        JobExecutor jobExecutor = new JobExecutor();
        JobReport jobReport = jobExecutor.execute(job);
        jobExecutor.shutdown();
        Assertions.assertThat(jobReport.getMetrics().getDuration()).isGreaterThanOrEqualTo(2 * 1000);// more than 2seconds
    }
```

I was playing around with this and it looks like it's working fine.

A more elaborate implemetation would use a throttling library (such as [guava](https://google.github.io/guava/releases/19.0/api/docs/index.html?com/google/common/util/concurrent/RateLimiter.html), [ratelimitj](https://github.com/mokies/ratelimitj), etc).

What do you think? Does this helps?

Kr
Mahmoud

**Comment by MALPI** [comment]
This looks good to me! Though we already worked around it. Still I think this feature is worth to be added.

**Comment by benas** [comment]
Great! glad it helps.

> Though we already worked around it

I'm curious, how did you do?


> Still I think this feature is worth to be added.

Indeed it's interesting, but this could be left to the user. I'm sure if we add a `ThrottlingRecordReader`, there would be someone saying why there is no `ThrottlingRecordWriter` 😄 and processor..

So since the implementation is pretty straightforward as shown in this issue, I would leave it to the user. What do you think?

**Comment by benas** [comment]
I'm closing this issue.

Since this feature can be implemented in several ways (reader, reader listener, writer listener, etc), it should be left to the user.

**Comment by mmodabber** [comment]
Although it is already closed, I would put the solution we used for.
We used the batch size,  let say 100 and then a customer batch-listener with this structure:

```
public class DelayBatchListener implements BatchListener {

  private final int batchLimitInSecond;

  /**
   * default constructor using parameters
   * @param batchLimitInSecond batch limit in second
   */
  public DelayBatchListener(int batchLimitInSecond) {
    this.batchLimitInSecond = batchLimitInSecond;
  }


  @Override
  public void beforeBatchReading() {
    /* No thing to do before the batch reading */
  }

  @Override
  public void afterBatchProcessing(Batch batch) {
    try {
      /* sleep for few second befor processing next batch */
      TimeUnit.SECONDS.sleep(batchLimitInSecond);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }
  }

  @Override
  public void afterBatchWriting(Batch batch) {
    /* No thing to do after batch writing */
  }

  @Override
  public void onBatchWritingException(Batch batch, Throwable throwable) {
    /* No thing to do when the batch writing facing exception */
  }
}
```

This would guarantee that the performance is 100 TPS in best case. of course it could be much more accurate and complex but I would say this is enough and yet simple for such purpose.
