### ISSUE TITLE
XmlRecordReader's escape-function is missing escaping for gt and lt 

### ISSUE THREAD

**Issue by Mercious** [j-easy/easy-batch#291]
I saw that you fixed the issue with the reader passing unescaped content to the mapper in 5.1.0 - however, it seems that the readers escape function only escapes 3 entities, missing gt and lt (<>). 
This causes issues when element's contain these character, as they become unencoded by the reader and then interpreted by the mapper. 
For example:
`<ValueTemplate>&lt;derive expr=&quot;{` becomes 
`<ValueTemplate><derive expr=&quot;{`
Now the mapper throws an exception because the attribute "expr" of supposed element (which it is not supposed to be) "derive" does not have an opening quotation mark.

**Comment by benas** [comment]
Thank you for pointing out this issue!

> I saw that you fixed the issue with the reader passing unescaped content to the mapper in 5.1.0

I guess you are talking about this: https://github.com/j-easy/easy-batch/blob/master/easybatch-xml/src/main/java/org/easybatch/xml/XmlRecordReader.java#L166

right?

>  however, it seems that the readers escape function only escapes 3 entities, missing gt and lt (<>).

There should be a good reason why < and > were not escaped, but to be honest, I don't remember it.

> This causes issues when element's contain these character

Is this allowed in xml? According to your example, the `XmlRecordReader` takes this:

`<ValueTemplate>&lt;derive expr=&quot;{`

and puts this in the payload of the xml record:

`<ValueTemplate><derive expr=&quot;{`

is this the case?

**Comment by Mercious** [comment]
Yes, that is the case, exactly as you have described. 
The issue with the reader is that the underlying reader it uses to retrieve payloads already does un-escaping of XML-entities. 
So before passing it on the mapper, you pretty much have to re-escape the whole thing. 
"&lt;derive expr=&quot;{" is valid content for an XML, since it's properly escaped.

**Comment by benas** [comment]
Hi @Mercious 

I've updated the `XmlRecordReader` to escape < and > in addition to other special characters.
Now, even if the input is escaped, the reader will keep it intact.

The fix is in v5.2.0-SNAPSHOT. It would be great if you give it a try and tell me if it works fine for you now. Thank you in advance!

Kr
Mahmoud

**Comment by benas** [comment]
@Mercious Have you got a chance to test the fix?

**Comment by Mercious** [comment]
@benas Yes, works fine now - thanks for the fix!

**Comment by benas** [comment]
Great! thanks for testing 👍
