### ISSUE TITLE
XmlRecordReader doesn't call getLocalPart() on QName

### ISSUE THREAD

**Issue by Mercious** [j-easy/easy-batch#292]
In XmLRecordReader.java, line 158:
`.append(attribute.getName())`
This should be (imho)
`.append(attribute.getName().getLocalPart())`

Without that getLocalPart() call the namespace is written before the actual attribute-name, resulting in stuff like
`<XmlElement {namespace}attributename="value"/>`
which isn't legit XML and thus causes issue when trying to map it. 

I believe this only happens with the very root element of the XML-document, probably because only there QName contains namespace-information. But that's just a guess.

**Comment by benas** [comment]
Hi @Mercious 

Thank you for pointing this out!

I will try to reproduce the issue. If you have a use case, please don't hesitate to provide it. It can help in writing a failing test and fixing the issue. You are welcome to contribute to the project with a pull request!

Kind regards
Mahmoud

**Comment by Mercious** [comment]
Thinking about this one, it might actually have been a problem on my side. I will have to double check that, chances are that the generated classes from xjc were missing some kind of XmlSchema-Annotation (which is usually set on package level). 
I will look into this again.

**Comment by benas** [comment]
Hi @Mercious 

Looks like the `XmlRecordReader` gets the local part from elements but not from attributes.

I've updated it to skip the namespace from attributes too. The fix is published in version 5.2.0-SNAPSHOT. Could you please give it a try and tell me if it is ok for you?

Many thanks upfront!

Kr
Mahmoud

**Comment by benas** [comment]
@Mercious Have you got a chance to test the fix?

**Comment by Mercious** [comment]
@benas Yes, works fine now - thanks for the fix!

**Comment by benas** [comment]
Oh Great! thank you for testing 👍
