### ISSUE TITLE
DefaultJobReportFormatter.formatReport Duration Rolls Over After 24 Hours

### ISSUE THREAD

**Issue by ipropper** [j-easy/easy-batch#293]
If your batch job exceeds 24 hours the `DefaultJobReportFormatter.formatReport`  duration hours field will roll over to 0.

example code:
```
 // Create the data source
        File dataSource = new File("src/main/resources/data/tweets.csv");

        // Build a batch job
        Job job = new JobBuilder()
                .named("hello world job")
                .reader(new FlatFileRecordReader(dataSource))
                .writer(new StandardOutputRecordWriter())
                .build();

        // Execute the job
        JobExecutor jobExecutor = new JobExecutor();
        JobReport report = jobExecutor.execute(job);
        jobExecutor.shutdown();

        // edit the duration of the job
        JobMetrics jobMetrics = new JobMetrics();
        jobMetrics.setStartTime(0);
        // one day in milliseconds
        jobMetrics.setEndTime(86400000);
        report.setMetrics(jobMetrics);

        // Print the job execution report
        System.out.println(report);
```
Produces the following output:
```
Start time = 1969-12-31 07:00:00
End time = 1970-01-01 07:00:00
Duration = 0hr 0min 0sec 0ms
```

With permission, I would like to create a pull request that will keep hours from rolling over. Sort of like [apache DurationFormatUtils](https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/time/DurationFormatUtils.html), but without including any libraries.  

This will allow the number of hours to exceed 23. For the above example it would print 

Duration = 24hr 0min 0sec 0ms

For 3 days, 10 minutes,  and 15 milliseconds, it would print:

Duration = 72hr 10min 0sec 15ms

etc.

**Comment by benas** [comment]
Hi,

Thank you for pointing this out! When I first introduced this duration format, I was not sure if there are batch jobs that may exceed one day, so I stopped in hours.. Looks like it was a wrong decision 😄 

Sure you are welcome to contribute to the project!

What do you think of adding a day section instead of letting hours exceed 23?
So For 3 days, 10 minutes, and 15 milliseconds, it would print:

Duration = 3d 0hr 10min 0sec 15ms

This is a more consistent format between time units. What do you think?

Kr
Mahmoud

**Comment by ipropper** [comment]
Adding days sounds good to me. I will get working on a pull request today!

**Comment by benas** [comment]
Hi @ipropper 

I've merged your PR and I'll include it in next release. Thank you for your time and effort!
I'm closing this issue.

Kr
Mahmoud
