### ISSUE TITLE
JobBuilder#enableJmx(boolean) method should not take a parameter

### ISSUE THREAD

**Issue by benas** [j-easy/easy-batch#297]
The `enableJmx` parameter is false by default.
According to the method `org.easybatch.core.job.JobBuilder#enableJmx(boolean)` name,  JMX monitoring will be set (so no need to specify `enableJmx(true)`). Hence, this method  should not take a parameter.

**Comment by DanieleS82** [comment]
Hi benas,
about this enhancement I have a doubt. In the work we are doing to write multithread jobs, we agree the template solution could be a nice solution. How shown in #299 commit, in the template solution is also provide utility methods to create the multithread job that accept in input a boolean flag to enable or not the monitoring. Removing the method 
```java
public JobBuilder enableJmx(final boolean jmx)
```
from JobBuilder, user is forced to write something like:
```java
JobBuilder jb = aNewJob().named(jobName).batchSize(batchSize);
if (jmx) {
  jb.enableJmx();
}
```
but if you mantain the function, is possible write:
```java
JobBuilder jb = aNewJob().named(jobName).batchSize(batchSize).enableJmx(jmx)
```
If the problem is the name of the method, you can reuse the same name of _parameters_ field
```java
public void setJmxMonitoring(final boolean jmx)
```
or provide both.

What do you think?

**Comment by benas** [comment]
Yes, the problem is the name of the method. saying "enableX" suppose the parameter X to be true, no need to specify `true` as parameter.

I'll deprecate the `enableJmx` in favor of a new setter `setJmxMonitoring` as you suggest.

Thank you for your feedback!

**Comment by benas** [comment]
> from JobBuilder, user is forced to write something like:
> 
> JobBuilder jb = aNewJob().named(jobName).batchSize(batchSize);
> if (jmx) {
>   jb.enableJmx();
> }

Looking at the code, indeed, I had to do this for the `JobFactoryBean` in spring extension:
https://github.com/j-easy/easy-batch/blob/master/easybatch-extensions/easybatch-spring/src/main/java/org/easybatch/extensions/spring/JobFactoryBean.java#L78

Just curious, what's wrong with that?

**Comment by DanieleS82** [comment]
It's not wrong, it's only for "elegance" because providing the setter method, you can write a single inline instruction to configure the _JobBuilerd_ but more important, you save a "if".

**Comment by benas** [comment]
Indeed, nothing wrong, just more code for the client in the end (which we don't want!).

Looking at how some other open source projects deal with that, I find that `enableJmx(boolean)` or `setEnableJmx(boolean)` are not that bad in the end:

* [eclipse kura](https://github.com/eclipse/kura/blob/5ab15411b32aa88a40bae2d1741d0d136a9677d6/kura/org.eclipse.kura.camel.cloud.factory/src/org/eclipse/kura/camel/cloud/factory/internal/ServiceConfiguration.java#L46)

* [apache james](https://github.com/apache/james-project/blob/81bf0a3c8c009b49a8c9bb4effd7a9af391b6469/server/mailet/integration-testing/src/test/java/org/apache/james/mailets/configuration/ProcessorConfiguration.java#L52)

* [apache camel](https://github.com/apache/camel/blob/87d4313c42a10db0c010920beb653c20666f767b/platforms/spring-boot/components-starter/camel-quartz2-starter/src/main/java/org/apache/camel/component/quartz2/springboot/QuartzComponentConfiguration.java#L126)

So I will revert the change and stick with the previous `enableJmx(boolean)` method.
