### ISSUE TITLE
AbstractFileRecordReader improvement

### ISSUE THREAD

**Issue by DanieleS82** [j-easy/easy-batch#301]
Hi @benas,
I have an idea to implement a new readers that take in input an _AbstractFileRecordReader_ but there is one issue. At the moment, the _file_ field is declared as protected and do not provide a getter, this limit the possibility to use the component. What do you think if we add the method to this abstract class? Do you see any issues? If you agree, I can do the change with the code of the new reader and submit the pull request.

**Comment by DanieleS82** [comment]
Hi @benas,
related to this issue, I wrote a new component that you can find in the pull request #302.
What do you think?

**Comment by benas** [comment]
Hi @DanieleS82 

No problem, we can add a getter for the file on `AbstractFileRecordReader`.

I've added a couple of notes on your PR.
Looking forward for your feedback.

Kr
Mahmoud

**Comment by benas** [comment]
Hi @DanieleS82 

I've added a getter for the file in the `AbstractFileRecordReader`.

I'm closing this issue.

Kr
Mahmoud
