### ISSUE TITLE
read from csv and get instances of records one by one

### ISSUE THREAD

**Issue by anasshs** [j-easy/easy-batch#306]
read from csv and get instance of records one by one, then print the result in the screen
//My file
File dataSource = new File("Z://FileTest//person.csv");
String[] fields = {"id", "name", "message"};
// Build a batch job
        Job job;
job = new JobBuilder()
				    .named("First Job")
				    .reader(new FlatFileRecordReader(dataSource))
				    .filter(new HeaderRecordFilter()) 	
				  line789  **.mapper(new DelimitedRecordMapper<>(Person.class,fields))**
				    **.writer(new StandardOutputRecordWriter())**
				//Not yet implemented  
                                    //.processor(new savetodb())
		                   //.validator(new BeanValidationRecordValidator())
		                 //	.processor( new copytoscreen())
				    .build();
				
JobExecutor jobExecutor = new JobExecutor();
 JobReport report = jobExecutor.execute(job);
 jobExecutor.shutdown();

			        // Print the job execution report
			        System.out.println(report);
			
		
	       

/////RESULTS

readandwrite.Person@212cf963
readandwrite.Person@ff092ac
readandwrite.Person@3d154580
readandwrite.Person@31de0d8
readandwrite.Person@453cf639
readandwrite.Person@4e5269c0

if i comment line 789 i get the results as shown here,

1,ertertertr,gjhdgfd
2,ertertret,fdgfdgfd
3,ertertertre,gfdfdgfdg
4,ertert,actigfddcall
5,anaerterss,acgfhgfhticall
6,terygert,gfhgfzsz

i need to instanciate data returned  from my csv,

any explication please

**Comment by benas** [comment]
You need to add a `toString` method to your `Person` class and it should work.

Basically what happens is that the `StandardOutputRecordWriter` is getting `Person` objects when you use the `DelimitedRecordMapper` (and writing persons without `toString` results in readandwrite.Person@212cf963, readandwrite.Person@ff092ac, etc).

If you comment the line 789, no mapping occurs and the writer gets raw strings as in the input file. Hence they are written as is.

Does this help?

**Comment by anasshs** [comment]
yes i do this befor getting you message; but when i specify an other csv file; it load the data of the first one;
//not used //File dataSource = new File("fileold.csv");
//used file 
File dataSource = new File("newfile.csv");

//result ; same as result before changing path

**Comment by benas** [comment]
> thank you, i do this and it works befor getting you message

ok so this is resolved

> but now when i specify an other csv file; it load the data of the first one;

This is not normal, make sure your reader reads data from the new file

> record length (44 fields) not equal to expected length of 3 fields

looks like indeed it is using the old configuration (`String[] fields = {"id", "name", "message"};`). Make sure to update the fields array with the new 44 fields.. Good luck! 😄

**Comment by yeddiraoui** [comment]
Hello Mohamed,
I'm using easy batch for encrypting over than 1000000 of data,
i'm having this issue when i run the job at the same line,
2018-09-26 09:42:13.040 SEVERE [org.easybatch.core.job.BatchJob processRecord] - Unable to process Record: {header=[number=161469, source="C:\ENGIE\batch\LIEN_ESPACE_PRIVE_COMPOSANTE.csv", creationDate="Wed Sep 26 09:42:13 CEST 2018"], payload=["6665782","CIVILITE;NOM;PRENOM;EMAIL;","Madame;xxxxxx;yyyyyyy;zzzzzzz]} 
java.lang.Exception: record length (3 fields) not equal to expected length of 6 fields

when un replace the line by an other, i have the same issue at the same line 161469.
