### ISSUE TITLE
Reading Json files w/o Array syntax wrappers

### ISSUE THREAD

**Issue by sasconsul** [j-easy/easy-batch#312]
I have some large files ~2 GB each that have been written as a simple stream of JSON objects.
These files can not be read with the **JsonRecordReader**.  The **JsonRecordReader** requires JSON array syntax
```
[
 { <JSON object> } ,
 { <JSON object> }, 
 { <JSON object> }
] 
```

I would like to be able to read the simple stream of JSON objects presented as:
```
 { <JSON object> }  
 { <JSON object> }  
 { <JSON object> } 
```
 
My current idea is to 'hack'  **JSONRecordReader** into **JSONStreamReader** by editing the hasNextRecord. 

BTW, I could have Overridden **JsonRecordReader::hasNextRecord()** if it was protected.

Am I on the right path?  Is this the right place for this type of issue?

Stuart

**Comment by benas** [comment]
You can read the json file as a flat file with a `FlatFileRecordReader`, then combine that with the `JsonRecordMapper` if you need to map each (json) line to a domain object.

Hope this helps.

**Comment by sasconsul** [comment]
Great idea,  I will work on that to process these "NDJson" records -- see [ndjson.org](http://ndjson.org) for details of the 'standard'.  We may even get a NdJsonRecordMapper from this  :).

**Comment by benas** [comment]
Sorry, my mistake. The `JsonRecordMapper` is planned (issue #261) but not released yet. It will be based on the reference implementation of JSON-B ( see [here](https://github.com/j-easy/easy-batch/wiki/mappers#json-to-object-mapping) ).

You can use the `JacksonRecordMapper` or the `GsonRecordMapper` for now.

**Comment by sasconsul** [comment]
Thank-you.  The GsonRecordMapper works well once I got the pom.xml file setup for using it.
