### ISSUE TITLE
Disable logging

### ISSUE THREAD

**Issue by MALPI** [j-easy/easy-batch#313]
Hey there,

we are using easybatch in our projects. Thanks for the great work!

I'd like to know if it's possible to deactivate logging of it completely or if there is an example on how to configure it in combination with slf4j.

**Comment by benas** [comment]
Hi,

> we are using easybatch in our projects. Thanks for the great work!

Thanks! Glad to hear that.

Easy Batch uses Java Util Logging, to disable it, you can set the logging level to [`OFF`](https://docs.oracle.com/javase/7/docs/api/java/util/logging/Level.html#OFF).

I consider moving to slf4j in a future version. It's simply better. If you want to contribute, you are welcome!

Kr
Mahmoud

**Comment by MALPI** [comment]
Ok, sounds great. I will file a PR!

**Comment by benas** [comment]
Great thanks!
