### ISSUE TITLE
Replace Java Util Logging with SLF4J

### ISSUE THREAD

**Issue by jcamiloradamesa** [j-easy/easy-batch#315]
I have been trying to configure easybatch with `spring-boot` and it have been a  nightmare to get logs redirecting to either log-back or log4j.  Even after being able to configure system fail with class-path errors. Spring boot guys mention in their documentation 

```
There are known classloading issues with Java Util Logging that cause problems when running from an ‘executable jar’. We recommend that you avoid it if at all possible.
```

I know that `we want the framework's core to have zero dependencies` but dont  you think is reasonable to think about this again? 

Note that was already mention
https://github.com/j-easy/easy-batch/issues/125

**Comment by benas** [comment]
yes, I consider moving to sl4fj, it is simply better.

**Comment by benas** [comment]
there will be probably a PR coming (see [here](https://github.com/j-easy/easy-batch/issues/313#issuecomment-378029750)). If not I will do it myself in next version.

**Comment by MALPI** [comment]
Sorry for the delay @benas, too much on the plate... I will definitely take care this week!

**Comment by benas** [comment]
@MALPI Oh no worries! take your time.

**Comment by benas** [comment]
Hi @jcamiloradamesa 

@MALPI has kindly replaced JUL with SFL4J 👍 
You can already give it a try with version 5.3.0-SNAPSHOT if you want.

Kr,
Mahmoud
