### ISSUE TITLE
Flat Map Functionality

### ISSUE THREAD

**Issue by IvanAtanasov** [j-easy/easy-batch#318]
Hi,

I am looking into using easy-batch for some simple ETL jobs and it looks very promising. One thing that seems to be missing however is something similar to a flatMap method. It would be used in cases where you have records that need to be split into multiple records.

For example if you have 3 records that are lists: [1,2,3], [3,4], [6,1] 

You could run a flatmap operation that creates 7 records like: 1,2,3,3,4,6,1

As far as I can tell doing something like this using easy-batch is impossible as the RecordProcessor simply takes one object and returns another.

Are there any solutions for this?

Thanks,
Ivan

**Comment by benas** [comment]
Hi,

The `flatmap` operation is not compatible with the processing model of easy batch where items are processed one at a time and then aggregated and written in batches.

What you can do is create an item reader that flatten records from lists of records and send them to the processing pipeline. Does this make sense?

Kr,
Mahmoud

**Comment by marcusdemian** [comment]
Hi
Can I popose an alternative solution ?
What I did to solve a similar case was create a customer Writer, extending BlockingQueueRecordWriter, when writing the record with "multiple internal records", loops over itens adding then to a new Batch.
So the next process, which reads the new Queue will have all records to process one by one.

**Comment by benas** [comment]
@marcusdemian Clever! So you basically use a queue as a buffer in which you flatten input records. Nice 👍

**Comment by benas** [comment]
> As far as I can tell doing something like this using easy-batch is impossible as the RecordProcessor simply takes one object and returns another.

As mentioned previously, record flattening should be done in a reader and not in a processor. In the example, a custom reader can take the list of lists and return items one by one. Another approach is to use a blocking queue as suggested by @marcusdemian .
