### ISSUE TITLE
Error Threshold - Zero Errors

### ISSUE THREAD

**Issue by IvanAtanasov** [j-easy/easy-batch#320]
Sorry another question..

The JobBuilder only allows the error threshold to be set to 1 or more. Surely in some cases people would want the threshold to be zero? Alternatively make the check in BatchJob >= rather than >.

```java
if (metrics.getErrorCount() > parameters.getErrorThreshold()) {
    throw new ErrorThresholdExceededException("Error threshold exceeded. Aborting execution", e);
}
```

I'm happy to raise a PR for this if you agree?

**Comment by benas** [comment]
makes sense, the builder should be updated to accept zero for the error threshold.

You are welcome to contribute if you want to open a PR! If you do, please don't hesitate to add your name to the list of contributors in the README file.

**Comment by IvanAtanasov89** [comment]
Added a PR for this: #325
