### ISSUE TITLE
process data before update

### ISSUE THREAD

**Issue by paraglohiya** [j-easy/easy-batch#323]
Hi I have below use case and i would like to use the easy batch framework to process it.

1. Read 1 data base table and get 4 columns from it.
2. Take this 4 column values and now create update statement to update 3 tables
e.g. update table A set column1 = ? where column1 = ? and column2 = ? and column3 = ? and column4 = ?
update table B set column1 = ? where column1 = ? and column2 = ?
update table A set column1 = ? where column1 = ? and column2 = ? and column3 = ?
This three commits should be part of 1 unit of work

In the above column1 value will be fetched from a couch base db view by querying it using values from step 1.

Is this type of mapping possible in easy batch?

Thanks!
Parag

**Comment by benas** [comment]
Yes, you can extend the `CompositeRecordWriter` and wrap its `writeRecords` method in a transaction. Otherwise, you can use a custom jdbc writer (similar to `JdbcRecordWriter`) that accepts multiple queries to be part of the same transaction.
