### ISSUE TITLE
when will be the next release version?

### ISSUE THREAD

**Issue by kpinjari** [j-easy/easy-batch#324]
Would like to understand when will be the next release? I see the current version is in JDK 1.7, any plans to upgrade to 1.8 or more latest JDK version in next release?

**Comment by benas** [comment]
The next release date is not defined for now. You can use v5.2.0 with Java 8 currently. The plan is to upgrade to Java 8 (or may be 11, a LTS version) in the next major version v6.

**Comment by benas** [comment]
Currently, the plan is to release:

* v5.3 by the end of June
* v6.0 by the end of December

NB: 5.3 will be the last feature version of 5.x line. I will still maintain this line for one year with only bug fixes if any.
