### ISSUE TITLE
Write valid XML with usage of XmlWrapperTagWiter failed

### ISSUE THREAD

**Issue by techteam-bln** [j-easy/easy-batch#330]
I generate different Objects with a pipe and finally I want it to write down into a file, with one root element.
My final job for this is:

```java
JobBuilder.aNewJob()
   .named("Joiner")
   .jobListener (new XmlWrapperTagWriter(file, "Report"))
   .reader( new BlockingQueueRecordReader(joinQueue, workers))
   .filter(new PoisonRecordFilter()
   .marshaller(new XmlRecordMarshaller<>(Unit.class))
   .writer(new FileRecordWirter(file))
   .build();
```

On start the XmlWrapperTagWriter writes the curent tag into the file but the FileRecordWriter ignores this content und starts with an new clean file. Afte job finish  the closing tag would be writen by the XmlWrapperTagWriter.

Is it a bug or a wrong configuration on my side?

**Comment by benas** [comment]
You need to open the writer in `append` mode. Please see [this tutorial](https://github.com/j-easy/easy-batch/tree/master/easybatch-tutorials/src/main/java/org/easybatch/tutorials/intermediate/csv2xml). In your case, it should be something like:

```
.writer(new FileRecordWirter(new FileWriter(file, true)))
```

Does this fix your issue?

**Comment by techteam-bln** [comment]
Sorry for my late answer.

Yes, fixed my issue - thanks a lot.
