### ISSUE TITLE
Add FileDirectoryWatcher

### ISSUE THREAD

**Issue by bgfeldm** [j-easy/easy-batch#332]
RecordReader which watches a directory for new files, and sends the new files to a sub RecordReader. With property to specify minimum age for new files. A file with a "creation time" of a few seconds old would avoid reading files being written to.

**Comment by benas** [comment]
This means when I run a job with such a reader, the job is never finished, since the reader is there watching the directory for changes. Do you agree?

For such use cases, I would schedule the job to run at the required frequency giving it as input the new files only.

**Comment by benas** [comment]
I'm closing this issue for the reason explained previously.
