### ISSUE TITLE
Add Header/Footer callbacks in FileRecordWriter

### ISSUE THREAD

**Issue by sheikhu** [j-easy/easy-batch#333]
Hi, @benas and all contributors,

Thanks for the great work, I've been using this for a short time, it's very lightweight and straightforward.

I would like to know how can I write a header for a FileRecordWriter, I need to do it before writing records.

I found some workaround but I don't really like it, I would like to see a better way to do this with easy batch.

Thank you in advance

**Comment by benas** [comment]
> I found some workaround but I don't really like it

Which workaround have you found?

The way to do it is to use a job listener. An example can be found in [this tutorial](https://github.com/j-easy/easy-batch/tree/master/easybatch-tutorials/src/main/java/org/easybatch/tutorials/intermediate/csv2xml). Note that the writer should be opened in `append` mode for this to work.

Does this help?

**Comment by sheikhu** [comment]
I've created a new BufferedFlatFileReader (i prefer it over Scanner), and add a new **withHeader** method wich receives a **StringRecord**. I override the open method with something like this:

```
super.open();
        if(this.header != null) {
            Batch headerBatch = new Batch();
            headerBatch.addRecord(this.header);
            super.writeRecords(headerBatch);
        }
```
so i do not need to open the file in append mode

It works pretty well but i would like to get your advice.

I also see the way that spring batch handles this case with the "FlatFileHeaderCallBack", but i will take a look at your tutorial above

Thank you for your feed abck

**Comment by benas** [comment]
Hi @sheikhu ,

I added two callback interfaces in `FileRecordWriter` called `HeaderCallback` and `FooterCallback` to write a header/footer in the output file.

This allows you to write a header/footer without having to open the file in append mode. I believe this approach is cleaner. You can find an example in the [header/footer tutorial](https://github.com/j-easy/easy-batch/tree/master/easybatch-tutorials/src/main/java/org/easybatch/tutorials/intermediate/headerfooter). It reads some tweets from a db and exports them in a CSV file. The output file contains a header with column names and a dynamic footer with the total number of records (this is a realistic and common use case).

I would be grateful if you could give it a try (using version [5.3.0-SNAPSHOT](https://github.com/j-easy/easy-batch/wiki/getting-started#use-a-snapshot-version)) and share your feedback.

Best regards,
Mahmoud
