### ISSUE TITLE
EasyBatch JMS multiple instances

### ISSUE THREAD

**Issue by bigzidane** [j-easy/easy-batch#334]
Hi,

If I have 2 instances of an application which are using easybatch with jms reader, what happens for the reader? is there any duplicated messages got process?

**Comment by benas** [comment]
The `JmsQueueRecordReader` is configured to read form a JMS queue. This means if you have multiple readers reading from the same queue, each reader will read distinct records. 

The behaviour you are concerned about would happen if the reader was configured with a JMS topic, not a queue.
