### ISSUE TITLE
Inefficient JobMetrics merge loops in DefaultJobReportMerger

### ISSUE THREAD

**Issue by verdi8** [j-easy/easy-batch#338]
In `DefaultJobReportMerger`, there are a few inefficient loops to increment the final report metrics from origin reports:
```
    private void calculateReadRecords(JobReport finalJobReport, JobReport jobReport) {
        for (int i = 0; i < jobReport.getMetrics().getReadCount(); i++) {
            finalJobReport.getMetrics().incrementReadCount();
        }
    }
```
Possible millions of `incrementReadCount()` could be avoided by a single `incrementReadCount(jobReport.getMetrics().getReadCount());`.

And also for `incrementWriteCount()` and `incrementErrorCount()`.

**Comment by verdi8** [comment]
PR coming soon.

**Comment by benas** [comment]
Awesome! Thank you for all these PRs!!

I'm busy finishing some ongoing tasks so please give me a couple of weeks to  and I will address those changes asap.
