### ISSUE TITLE
AppVeyor build failures

### ISSUE THREAD

**Issue by verdi8** [j-easy/easy-batch#340]
Recent pull requests #325, #326 and #339 have the following AppVeyor build failure :
`[FATAL] Non-resolvable parent POM for org.easybatch:easybatch:5.3.0-SNAPSHOT: Could not transfer artifact org.sonatype.oss:oss-parent:pom:7 from/to central (https://repo.maven.apache.org/maven2): Received fatal alert: protocol_version and 'parent.relativePath' points at wrong local POM @ line 5, column 13 `

It may be caused by the OSS Sonatype parent POM that is deprecated, see: https://github.com/sonatype/oss-parents

**Comment by benas** [comment]
Thank you for raising this. It was in the pipe. Fixed in 8c3e2f9ba9fac1bd6be10b6d5c0d558e1b401852.
