### ISSUE TITLE
Add chunk processing support

### ISSUE THREAD

**Issue by verdi8** [j-easy/easy-batch#342]
Similar to #87 but on current version.

Usual batch treatments consist in : (1) read ids from DB, (2) process the ids by reading a complete enriched object from DB, (3) marshall the object, (4) write the object to a file (or other stream). Steps (2) and (3) processing can usually be accelerated by reading objects by small chunks (because of caches along the data chain).

**Design proposal :** 
- Introduce a new type of `Record`: `ChunkRecord` that is a `GenericRecord<List<T>>`

- Introduce a new type of `RecordReader` named `ChunkRecordReader` that 
   - wraps a standard `RecordReader` for multiple `readRecord()` calls
   - generates a ChunkRecord object whose
      - payload is a `List` of the origin payloads
      - header is the `Header` of the first `Record` in the chunk

- The most impacting stuff : to avoid job metrics counts getting wrong when using chunks
   - add a `long size()` (or weight() ?) method to the `Record` interface to give it a size.
     - It returns a default `1` in `GenericRecord`(and thus in all its subclasses)
     - It returns a default `0` in `PoisonRecord`
     - It returns the real size of the `ChunkRecord` content
   - use this `size()` in all metrics count increments (#339 will be useful :-))

- Introduce a new type of `RecordWriter` named `ChunkRecordWriter` that transforms a single `writeRecords(Batch batch)` call into multiple call to a wrapped `RecordWriter` by reconstructing `Batch`es of the same size.

- Dedicated documentation page for chunk usage

**Comment by verdi8** [comment]
Waiting for validation to start a PR

**Comment by benas** [comment]
Hi @verdi8 ,

Thank you for opening this issue. As of version 6 released recently, my goal is to keep the API as stable as possible and to slim things down to a bare minimum (See [release notes](https://github.com/j-easy/easy-batch/releases/tag/easy-batch-6.0.0)). Hence, I'm not ready to introduce such big changes for now, those can be done in a fork. If you think these new concepts can be added without any breaking change, then please create an extension that you own and maintain and I will be more than happy to add a link to it in the home page.

Best regards,
Mahmoud
