### ISSUE TITLE
HtmlJobReportFormatter - Accept velocity params (log location)

### ISSUE THREAD

**Issue by psoares-resilient** [j-easy/easy-batch#345]
Hi, 

the public constructor is 
```
 public HtmlJobReportFormatter() {
        Properties properties = new Properties();
        properties.put("resource.loader", "class");
        properties.put("class.resource.loader.class", "org.apache.velocity.runtime.resource.loader.ClasspathResourceLoader");
        velocityEngine = new VelocityEngine(properties);
        velocityEngine.init();
    }
```

a `velocity.log` is written in the FS when run, however when running in environments that are readonly (ie AWS Lambda) we have to specify the location of the logs. Adding this 
 `properties.put("runtime.log", "/tmp/velocity.log");` creates the log in the right location. 

Can we have a constructor that accepts some options?

Thanks!

**Comment by benas** [comment]
Hi @psoares-resilient,

Thank you for reporting this issue! I consider this as a bug in Easy Batch: As a user, I should not be aware that the `HtmlJobReportFormatter` is using apache velocity behind the scene and I should not be concerned with its configuration. The reporter should not generate any log so I disabled it.
