### ISSUE TITLE
Extention documentation

### ISSUE THREAD

**Issue by nizar2yas** [j-easy/easy-batch#346]
I'm trying to get started with easybatch, however, I don't find documentation, meanly for extensions , I looked in the java doc -> extensions, but I'm getting this message all the time :

> org.easybatch:easybatch-extensions:5.2.0: Javadoc is being downloaded. Normally this will be completed within 10 minutes. Please refresh page again later.

could anyone help please.

**Comment by benas** [comment]
`easybatch-extensions` is the parent module of all extensions. It is of packaging type `pom` and not `jar` so it does not have any javadoc. Javadoc.io should not show these types of modules (or at least warn the user about the attempt of viewing non-existing javadocs).

If you want to see the javadoc of a specific extension on javadoc.io, you need to select the extension you want (in the url or via in [menu](https://www.javadoc.io/doc/org.easybatch)). Here is an example for `easybatch-gson` extension: https://www.javadoc.io/doc/org.easybatch/easybatch-gson/latest/index.html
