### ISSUE TITLE
Any working example available?

### ISSUE THREAD

**Issue by bsudhir6** [j-easy/easy-batch#371]
Hi I am new to batch programming. Can you tell me if there's any working example is available for using easy-batch?

I am looking to create a batch job that stores file locations in DB and retrieve the file locations from DB to process and store the information on to DB.

Thanks

**Comment by benas** [comment]
> Can you tell me if there's any working example is available for using easy-batch?

You can find complete tutorials here: https://github.com/j-easy/easy-batch/tree/master/easy-batch-tutorials.
