### ISSUE TITLE
Json Line reader support

### ISSUE THREAD

**Issue by vinay-sd17** [j-easy/easy-batch#373]
Hi Team,

How can I make use of jEasyBatch to marshall the multiple JSON Line records document?

Example input document:

```json
{"valueName":"GPS_latitude","valueType":"-1","value":"39.26842508","objectID":"charger_80","timestamp":"1556841594000"}
{"valueName":"GPS_longitude","valueType":"-1","value":"-76.60410104","objectID":"charger_80","timestamp":"1556841594000"}
````

Output: (Something like) List<Gps>

**Comment by benas** [comment]
Is the input document a [ndjson](http://ndjson.org) file or is there a wapper array `[..]` around records?

**Comment by vinay-sd17** [comment]
Yes its ndjson file format. Each record has delimited by \n

Like this
 {"some":"thing"}
 {"foo":17,"bar":false,"quux":true}
 {"may":{"include":"nested","objects":["and","arrays"]}}

**Comment by benas** [comment]
ok thanks. You will need a custom reader for that, the [recipe tutorial](https://github.com/j-easy/easy-batch/tree/master/easy-batch-tutorials/src/main/java/org/jeasy/batch/tutorials/advanced/recipes) might help. It shows how to read logical records that span multiple physical lines.
