### ISSUE TITLE
Question : About writer line by line 

### ISSUE THREAD

**Issue by old741** [j-easy/easy-batch#382]
Hello ,
i use v5.3.0
Is it possible to write line by line instead of loading all into memory and writing it batch by batch in csv file at the end ?
If possible how do it ?
Thanks

**Comment by benas** [comment]
Hi,

You can do that by setting the batch size to 1, see [job configuration](https://github.com/j-easy/easy-batch/wiki/job-configuration#job-parameters). The idea of bulk writes is to flush records in batches instead of one by one for better performance (jdbc batch updates is the typical use case).
