### ISSUE TITLE
Export data from MongoDb to file

### ISSUE THREAD

**Issue by vinay-sd17** [j-easy/easy-batch#383]
Team, Is it not possible to export records from MongoDB to a flat file? 

If so can I get some example using JPA

**Comment by benas** [comment]
> Is it not possible to export records from MongoDB to a flat file?

MongoDB support has been dropped in v6 (see #354), but you can still grab the code from the latest v5 branch if you want: https://github.com/j-easy/easy-batch/blob/easybatch-5.3.0/easybatch-extensions/easybatch-mongodb/src/main/java/org/easybatch/extensions/mongodb/MongoDBRecordReader.java.

> If so can I get some example using JPA

There is no full tutorial for JPA support, but the test cases should help you: https://github.com/j-easy/easy-batch/tree/6e0d7966bc243b82b5f1222755b0cbe561437aba/easy-batch-jpa/src/test/java/org/jeasy/batch/jpa
