### ISSUE TITLE
can we stop to create file when they are no values

### ISSUE THREAD

**Issue by old741** [j-easy/easy-batch#384]
Hello ,
i use v5.3.0
I use JdbcRecordReader and writer. 
I want write in my file if only my query return at least one line.
How can I do it please ?

**Comment by old741** [comment]
On spring batch it s writer.setShouldDeleteIfEmpty(true);
How do it on EasyBatch  ?

**Comment by benas** [comment]
You can't do it with the `FileRecordWriter`. It is not the responsibility of the writer to delete or move the file if no records have been written. You can do that using a `JobListener#afterJob` instead, something like:

```java
public void afterJob(JobReport jobReport) {
    if (jobReport.getMetrics().getWriteCount() == 0) {
        delete(yourFile);
    }
}
```

**Comment by old741** [comment]
Thank you !
