### ISSUE TITLE
Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1

### ISSUE THREAD

**Issue by mikeyong** [j-easy/easy-batch#39]
I'm trying the easy batch tutorials and facing the problem below:

C:\test\BatchFramework\easy-batch-master\easybatch-tutorials>mvn exec:java -PrunHelloWorldCSVTutorial
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/apache-maven-3.2.3/lib/slf4j-simple-1.7.5%20(2).jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/apache-maven-3.2.3/lib/slf4j-simple-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.SimpleLoggerFactory]
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/apache-maven-3.2.3/lib/slf4j-simple-1.7.5%20(2).jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/apache-maven-3.2.3/lib/slf4j-simple-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.SimpleLoggerFactory]
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building easybatch-tutorials 2.2.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] >>> exec-maven-plugin:1.2.1:java (default-cli) > validate @ easybatch-tutorials >>>
[INFO]
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ easybatch-tutorials ---
[INFO]
[INFO] <<< exec-maven-plugin:1.2.1:java (default-cli) < validate @ easybatch-tutorials <<<
[INFO]
[INFO] --- exec-maven-plugin:1.2.1:java (default-cli) @ easybatch-tutorials ---
[WARNING]
java.lang.ClassNotFoundException: org.easybatch.tutorials.helloworld.csv.Launcher
        at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:285)
        at java.lang.Thread.run(Thread.java:745)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.872 s
[INFO] Finished at: 2014-12-17T20:59:30+08:00
[INFO] Final Memory: 9M/181M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:java (default-cli) on project easybatch-tutorials: An exception occured while executing the Java class. org.easybatch.tutorials.helloworld.csv.Launcher -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
C:\test\BatchFramework\easy-batch-master\easybatch-tutorials>mvn -version
Apache Maven 3.2.3 (33f8c3e1027c3ddde99d3cdebad2656a31e8fdf4; 2014-08-12T04:58:10+08:00)
Maven home: C:\apache-maven-3.2.3
Java version: 1.8.0_11, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_11\jre
Default locale: en_SG, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "dos"
C:\test\BatchFramework\easy-batch-master\easybatch-tutorials>

**Comment by RazmikMkrtchyan** [comment]
Hi @benas ,
Thank you for helpful  answer.

**Comment by benas** [comment]
Hi @RazmikMkrtchyan 

You are welcome! I'm willing to help if you need further support.

Kind regards
Mahmoud
