### ISSUE TITLE
Support java8

### ISSUE THREAD

**Issue by cn-src** [j-easy/easy-batch#391]
Can the latest version support java8, because it is currently the most used version.

**Comment by benas** [comment]
No, Easy Batch v7 is compiled against Java 11. You can use v6.1 on Java 8. Feature wise, v7 is the same as v6.1 except the removal of deprecated APIs and more type safe APIs (see the [release notes](https://github.com/j-easy/easy-batch/releases/tag/easy-batch-7.0.0)).
