### ISSUE TITLE
Customize the monitor

### ISSUE THREAD

**Issue by cn-src** [j-easy/easy-batch#392]
Hi, How to customize the monitor? I don't want to use jmx, because each job needs to use a different name, which will cause a lot of mbeans.

**Comment by benas** [comment]
The job monitor is designed to work with JMX APIs (note how it is located in the `org.jeasy.batch.core.jmx` package). If you don't want to use JMX, you can implement a custom monitor using the provided [listeners](https://github.com/j-easy/easy-batch/wiki/listeners).
